name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - run: yarn
    - run: yarn test node
    - run: yarn test php7